#ifndef TESTCELL_H
#define TESTCELL_H

#include <iostream>
#include <string>
#include <sstream>

#include "../cell.h"

using namespace std;

class TestCell
{
public:

    // PUBLIC METHODS

    /********************************************************************
    Default constructor
    ********************************************************************/
    TestCell();

    /********************************************************************
    Runs all defined testing functions and prints the errors generated by
    those functions.

    @return
        The printed output of the functions
    ********************************************************************/
    string allTests( );

    /********************************************************************
    Automated testing for the Cell Constructor. Prints failed test cases.

    @return
        The printed output of the function
    ********************************************************************/
    string testConstructor( );

    /********************************************************************
    Automated testing for Cell::step( ). Prints failed test cases.

    @return
        The printed output of the function
    ********************************************************************/
    string testStep( );

    /********************************************************************
    Automated testing for Cell::evolve( ). Prints failed test cases.

    @return
        The printed output of the function
    ********************************************************************/
    string testEvolve( );

    /********************************************************************
    Automated testing for Cell::assign_apoptosis( ). Prints failed test
    cases.

    @return
        The printed output of the function
    ********************************************************************/
    string testAssign_Apoptosis( );

    /********************************************************************
    Automated testing for Cell::assign_proliferation( ). Prints failed
    test cases.

    @return
        The printed output of the function
    ********************************************************************/
    string testAssign_Proliferation( );

    /********************************************************************
    Automated testing for Cell::assign_differentiation( ). Prints failed
    test cases.

    @return
        The printed output of the function
    ********************************************************************/
    string testAssign_Differentiation( );

    /********************************************************************
    Automated testing for Cell::assign_move( ). Prints failed test cases.

    @return
        The printed output of the function
    ********************************************************************/
    string testAssign_Move( );
};

#endif // TESTCELL_H
