%PI=round(LHS_Call(min, mean, max, std, runs, `type`)
clear;
runs=300; 


% 6 Differentiation
DIFFERENTIATED_SPERMATOGONIA_DIFFERENTIATION_s= 205;
PRELEPTOTENE_DIFFERENTIATION_s= 44;
LEPTOTENE_DIFFERENTIATION_s= 24;
ZYGOTENE_DIFFERENTIATION_s= 42;
PACHYTENE_DIFFERENTIATION_s= 165;
ROUND_SPERMATIDS_DIFFERENTIATION_s= 126;

% 3 Proliferation
DIFFERENTIATED_SPERMATOGONIA_PROLIFERATION_s=88;
DIPLOTENE_PROLIFERATION_s=20;
SECOND_SPERMATOCTYE_PROLIFERATION_s=22; 

% 9 Apoptosis Min
DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MIN_s=206;
PRELEPTOTENE_APOPTOSIS_MIN_s=43;
LEPTOTENE_APOPTOSIS_MIN_s=23;
ZYGOTENE_APOPTOSIS_MIN_s=41;
PACHYTENE_APOPTOSIS_MIN_s=164;
DIPLOTENE_APOPTOSIS_MIN_s=21;
SECOND_SPERMATOCTYE_APOPTOSIS_MIN_s=22;
ROUND_SPERMATIDS_APOPTOSIS_MIN_s=125;
ELONGATED_SPERMATIDS_APOPTOSIS_MIN_s=200;


% 9 Apoptosis Max
DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MAX_s=206;
PRELEPTOTENE_APOPTOSIS_MAX_s=93;
LEPTOTENE_APOPTOSIS_MAX_s=73;
ZYGOTENE_APOPTOSIS_MAX_s=91;
PACHYTENE_APOPTOSIS_MAX_s=214;
DIPLOTENE_APOPTOSIS_MAX_s=23;
SECOND_SPERMATOCTYE_APOPTOSIS_MAX_s=25;
ROUND_SPERMATIDS_APOPTOSIS_MAX_s=175;
ELONGATED_SPERMATIDS_APOPTOSIS_MAX_s=230;


% 10 Speed
UNDIFFERENTIATED_SPERMATOGONIA_SPEED_s=60;
DIFFERENTIATED_SPERMATOGONIA_SPEED_s=10;
PRELEPTOTENE_SPEED_s=40;
LEPTOTENE_SPEED_s=10;
ZYGOTENE_SPEED_s=40;
PACHYTENE_SPEED_s=20;
DIPLOTENE_SPEED_s=5;
SECOND_SPERMATOCTYE_SPEED_s=5;
ROUND_SPERMATIDS_SPEED_s=20;
ELONGATED_SPERMATIDS_SPEED_s=60;

% 1 Initial number of cells in simulation
UNDIFFERENTIATED_SPERMATOGONIA_INITIAL_NUM_s=8;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%6 DIFFERENTIATION LHS
DIFFERENTIATED_SPERMATOGONIA_DIFFERENTIATION=round(LHS_Call((0.5*DIFFERENTIATED_SPERMATOGONIA_DIFFERENTIATION_s),DIFFERENTIATED_SPERMATOGONIA_DIFFERENTIATION_s,(1.5*DIFFERENTIATED_SPERMATOGONIA_DIFFERENTIATION_s), 0 ,runs,'unif'));
PRELEPTOTENE_DIFFERENTIATION=round(LHS_Call((0.5*PRELEPTOTENE_DIFFERENTIATION_s),PRELEPTOTENE_DIFFERENTIATION_s,(1.5*PRELEPTOTENE_DIFFERENTIATION_s), 0 ,runs,'unif'));
LEPTOTENE_DIFFERENTIATION=round(LHS_Call((0.5*LEPTOTENE_DIFFERENTIATION_s),LEPTOTENE_DIFFERENTIATION_s,(1.5*LEPTOTENE_DIFFERENTIATION_s), 0 ,runs,'unif'));
ZYGOTENE_DIFFERENTIATION=round(LHS_Call((0.5*ZYGOTENE_DIFFERENTIATION_s),ZYGOTENE_DIFFERENTIATION_s,(1.5*ZYGOTENE_DIFFERENTIATION_s), 0 ,runs,'unif'));
PACHYTENE_DIFFERENTIATION=round(LHS_Call((0.5*PACHYTENE_DIFFERENTIATION_s),PACHYTENE_DIFFERENTIATION_s,(1.5*PACHYTENE_DIFFERENTIATION_s), 0 ,runs,'unif'));
ROUND_SPERMATIDS_DIFFERENTIATION=round(LHS_Call((0.5*ROUND_SPERMATIDS_DIFFERENTIATION_s),ROUND_SPERMATIDS_DIFFERENTIATION_s,(1.5*ROUND_SPERMATIDS_DIFFERENTIATION_s), 0 ,runs,'unif'));


% 3 PROLIFERATION
DIFFERENTIATED_SPERMATOGONIA_PROLIFERATION=round(LHS_Call((0.5*DIFFERENTIATED_SPERMATOGONIA_PROLIFERATION_s),DIFFERENTIATED_SPERMATOGONIA_PROLIFERATION_s,(1.5*DIFFERENTIATED_SPERMATOGONIA_PROLIFERATION_s), 0 ,runs,'unif'));
DIPLOTENE_PROLIFERATION=round(LHS_Call((0.5*DIPLOTENE_PROLIFERATION_s),DIPLOTENE_PROLIFERATION_s,(1.5*DIPLOTENE_PROLIFERATION_s), 0 ,runs,'unif'));
SECOND_SPERMATOCTYE_PROLIFERATION=round(LHS_Call((0.5*SECOND_SPERMATOCTYE_PROLIFERATION_s),SECOND_SPERMATOCTYE_PROLIFERATION_s,(1.5*SECOND_SPERMATOCTYE_PROLIFERATION_s), 0 ,runs,'unif'));


%9 APOPTOSIS_MIN LHS
DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MIN=round(LHS_Call((0.5*DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MIN_s),DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MIN_s,DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
PRELEPTOTENE_APOPTOSIS_MIN=round(LHS_Call((0.5*PRELEPTOTENE_APOPTOSIS_MIN_s),PRELEPTOTENE_APOPTOSIS_MIN_s,PRELEPTOTENE_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
LEPTOTENE_APOPTOSIS_MIN=round(LHS_Call((0.5*LEPTOTENE_APOPTOSIS_MIN_s),LEPTOTENE_APOPTOSIS_MIN_s,LEPTOTENE_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
ZYGOTENE_APOPTOSIS_MIN=round(LHS_Call((0.5*ZYGOTENE_APOPTOSIS_MIN_s),ZYGOTENE_APOPTOSIS_MIN_s,ZYGOTENE_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
PACHYTENE_APOPTOSIS_MIN=round(LHS_Call((0.5*PACHYTENE_APOPTOSIS_MIN_s),PACHYTENE_APOPTOSIS_MIN_s,PACHYTENE_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
DIPLOTENE_APOPTOSIS_MIN=round(LHS_Call((0.5*DIPLOTENE_APOPTOSIS_MIN_s),DIPLOTENE_APOPTOSIS_MIN_s,DIPLOTENE_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
SECOND_SPERMATOCTYE_APOPTOSIS_MIN=round(LHS_Call((0.5*SECOND_SPERMATOCTYE_APOPTOSIS_MIN_s),SECOND_SPERMATOCTYE_APOPTOSIS_MIN_s,SECOND_SPERMATOCTYE_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
ROUND_SPERMATIDS_APOPTOSIS_MIN=round(LHS_Call((0.5*ROUND_SPERMATIDS_APOPTOSIS_MIN_s),ROUND_SPERMATIDS_APOPTOSIS_MIN_s,ROUND_SPERMATIDS_APOPTOSIS_MAX_s, 0 ,runs,'unif'));
ELONGATED_SPERMATIDS_APOPTOSIS_MIN=round(LHS_Call((0.5*ELONGATED_SPERMATIDS_APOPTOSIS_MIN_s),ELONGATED_SPERMATIDS_APOPTOSIS_MIN_s,ELONGATED_SPERMATIDS_APOPTOSIS_MAX_s, 0 ,runs,'unif'));


%10 SPEED LHS
UNDIFFERENTIATED_SPERMATOGONIA_SPEED=round(LHS_Call((0.5*UNDIFFERENTIATED_SPERMATOGONIA_SPEED_s),UNDIFFERENTIATED_SPERMATOGONIA_SPEED_s,(1.5*UNDIFFERENTIATED_SPERMATOGONIA_SPEED_s), 0 ,runs,'unif'));
DIFFERENTIATED_SPERMATOGONIA_SPEED=round(LHS_Call((0.5*DIFFERENTIATED_SPERMATOGONIA_SPEED_s),DIFFERENTIATED_SPERMATOGONIA_SPEED_s,(1.5*DIFFERENTIATED_SPERMATOGONIA_SPEED_s), 0 ,runs,'unif'));
PRELEPTOTENE_SPEED=round(LHS_Call((0.5*PRELEPTOTENE_SPEED_s),PRELEPTOTENE_SPEED_s,(1.5*PRELEPTOTENE_SPEED_s), 0 ,runs,'unif'));
LEPTOTENE_SPEED=round(LHS_Call((0.5*LEPTOTENE_SPEED_s),LEPTOTENE_SPEED_s,(1.5*LEPTOTENE_SPEED_s), 0 ,runs,'unif'));
ZYGOTENE_SPEED=round(LHS_Call((0.5*ZYGOTENE_SPEED_s),ZYGOTENE_SPEED_s,(1.5*ZYGOTENE_SPEED_s), 0 ,runs,'unif'));
PACHYTENE_SPEED=round(LHS_Call((0.5*PACHYTENE_SPEED_s),PACHYTENE_SPEED_s,(1.5*PACHYTENE_SPEED_s), 0 ,runs,'unif'));
DIPLOTENE_SPEED=round(LHS_Call((0.5*DIPLOTENE_SPEED_s),DIPLOTENE_SPEED_s,(1.5*DIPLOTENE_SPEED_s), 0 ,runs,'unif'));
SECOND_SPERMATOCTYE_SPEED=round(LHS_Call((0.5*SECOND_SPERMATOCTYE_SPEED_s),SECOND_SPERMATOCTYE_SPEED_s,(1.5*SECOND_SPERMATOCTYE_SPEED_s), 0 ,runs,'unif'));
ROUND_SPERMATIDS_SPEED=round(LHS_Call((0.5*ROUND_SPERMATIDS_SPEED_s),ROUND_SPERMATIDS_SPEED_s,(1.5*ROUND_SPERMATIDS_SPEED_s), 0 ,runs,'unif'));
ELONGATED_SPERMATIDS_SPEED=round(LHS_Call((0.5*ELONGATED_SPERMATIDS_SPEED_s),ELONGATED_SPERMATIDS_SPEED_s,(1.5*ELONGATED_SPERMATIDS_SPEED_s), 0 ,runs,'unif'));

%1 UNDIFFERENTIATED NUMBER
UNDIFFERENTIATED_SPERMATOGONIA_INITIAL_NUM=(round(LHS_Call((0.5*UNDIFFERENTIATED_SPERMATOGONIA_INITIAL_NUM_s),UNDIFFERENTIATED_SPERMATOGONIA_INITIAL_NUM_s,(1.5*UNDIFFERENTIATED_SPERMATOGONIA_INITIAL_NUM_s), 0 ,runs,'unif')));


LHS_Final=[DIFFERENTIATED_SPERMATOGONIA_DIFFERENTIATION PRELEPTOTENE_DIFFERENTIATION LEPTOTENE_DIFFERENTIATION ZYGOTENE_DIFFERENTIATION PACHYTENE_DIFFERENTIATION ROUND_SPERMATIDS_DIFFERENTIATION DIFFERENTIATED_SPERMATOGONIA_PROLIFERATION DIPLOTENE_PROLIFERATION SECOND_SPERMATOCTYE_PROLIFERATION DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MIN PRELEPTOTENE_APOPTOSIS_MIN LEPTOTENE_APOPTOSIS_MIN ZYGOTENE_APOPTOSIS_MIN PACHYTENE_APOPTOSIS_MIN DIPLOTENE_APOPTOSIS_MIN SECOND_SPERMATOCTYE_APOPTOSIS_MIN ROUND_SPERMATIDS_APOPTOSIS_MIN ELONGATED_SPERMATIDS_APOPTOSIS_MIN UNDIFFERENTIATED_SPERMATOGONIA_SPEED DIFFERENTIATED_SPERMATOGONIA_SPEED PRELEPTOTENE_SPEED LEPTOTENE_SPEED ZYGOTENE_SPEED PACHYTENE_SPEED DIPLOTENE_SPEED SECOND_SPERMATOCTYE_SPEED ROUND_SPERMATIDS_SPEED ELONGATED_SPERMATIDS_SPEED UNDIFFERENTIATED_SPERMATOGONIA_INITIAL_NUM]';

LHS_Final=num2cell(LHS_Final);




Names={'DIFFERENTIATED_SPERMATOGONIA_DIFFERENTIATION' 'PRELEPTOTENE_DIFFERENTIATION' 'LEPTOTENE_DIFFERENTIATION' 'ZYGOTENE_DIFFERENTIATION' 'PACHYTENE_DIFFERENTIATION' 'ROUND_SPERMATIDS_DIFFERENTIATION' 'DIFFERENTIATED_SPERMATOGONIA_PROLIFERATION' 'DIPLOTENE_PROLIFERATION' 'SECOND_SPERMATOCTYE_PROLIFERATION' 'DIFFERENTIATED_SPERMATOGONIA_APOPTOSIS_MIN' 'PRELEPTOTENE_APOPTOSIS_MIN' 'LEPTOTENE_APOPTOSIS_MIN' 'ZYGOTENE_APOPTOSIS_MIN' 'PACHYTENE_APOPTOSIS_MIN' 'DIPLOTENE_APOPTOSIS_MIN' 'SECOND_SPERMATOCTYE_APOPTOSIS_MIN' 'ROUND_SPERMATIDS_APOPTOSIS_MIN' 'ELONGATED_SPERMATIDS_APOPTOSIS_MIN' 'UNDIFFERENTIATED_SPERMATOGONIA_SPEED' 'DIFFERENTIATED_SPERMATOGONIA_SPEED' 'PRELEPTOTENE_SPEED' 'LEPTOTENE_SPEED' 'ZYGOTENE_SPEED' 'PACHYTENE_SPEED' 'DIPLOTENE_SPEED' 'SECOND_SPERMATOCTYE_SPEED' 'ROUND_SPERMATIDS_SPEED' 'ELONGATED_SPERMATIDS_SPEED' 'UNDIFFERENTIATED_SPERMATOGONIA_INITIAL_NUM'}';


k=repmat('%.2f\t',1,runs);


filename= 'my.txt'; 
fid=fopen(filename,'w');

for row =1:length(Names)
    
    fprintf(fid,'%s\t',Names{row,:});
    fprintf(fid,k, LHS_Final{row,:});
    fprintf(fid,'\n');
 end
 fclose(fid);

 % NEEDED WHILE RUNNING FROM TERMINAL
 %exit





















